name = "Examples"
uuid = "abb6aba6-a5dd-11eb-1a42-65499bd4c243"
authors = ["Danylo Malyuta <danylo@malyuta.name>", "Taylor P. Reynolds", "Michael Szmuk", "Thomas Lew", "Riccardo Bonalli", "Marco Pavone", "Behcet Acikmese"]
version = "1.0.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parser = "8531126a-8d07-4702-a998-a66a2313e289"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Solvers = "7328b228-a5db-11eb-3781-05e2836e9a59"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Utils = "8b916518-a5eb-11eb-206d-83b0b19bff08"
